REM this is the actual script used for R2 --> R3 upgrade

REM delete the existing FHIR Specification

del *.* /q
rmdir Account /s /q
rmdir account-status /s /q
rmdir actionlist /s /q
rmdir additionalmaterials /s /q
rmdir Address /s /q
rmdir address-type /s /q
rmdir address-use /s /q
rmdir adjudication /s /q
rmdir adjudication-error /s /q
rmdir adjustment-reason /s /q
rmdir administrative-gender /s /q
rmdir admit-source /s /q
rmdir Age /s /q
rmdir AllergyIntolerance /s /q
rmdir allergy-intolerance-category /s /q
rmdir allergy-intolerance-criticality /s /q
rmdir allergy-intolerance-status /s /q
rmdir allergy-intolerance-type /s /q
rmdir animal-breed /s /q
rmdir animal-genderstatus /s /q
rmdir animal-species /s /q
rmdir Annotation /s /q
rmdir answer-format /s /q
rmdir Appointment /s /q
rmdir AppointmentResponse /s /q
rmdir appointmentstatus /s /q
rmdir argonaut /s /q
rmdir assert-direction-codes /s /q
rmdir assert-operator-codes /s /q
rmdir assert-response-code-types /s /q
rmdir assets /s /q
rmdir Attachment /s /q
rmdir AuditEvent /s /q
rmdir audit-event-action /s /q
rmdir audit-event-outcome /s /q
rmdir audit-event-type /s /q
rmdir BackboneElement /s /q
rmdir base64Binary /s /q
rmdir Basic /s /q
rmdir basic-resource-type /s /q
rmdir Binary /s /q
rmdir binding-strength /s /q
rmdir BodySite /s /q
rmdir boolean /s /q
rmdir Bundle /s /q
rmdir bundle-type /s /q
rmdir canonicalization /s /q
rmdir CarePlan /s /q
rmdir care-plan-activity-category /s /q
rmdir care-plan-activity-status /s /q
rmdir care-plan-relationship /s /q
rmdir care-plan-status /s /q
rmdir choice-list-orientation /s /q
rmdir Claim /s /q
rmdir ClaimResponse /s /q
rmdir claim-type-link /s /q
rmdir claim-use-link /s /q
rmdir classification-or-context /s /q
rmdir ClinicalImpression /s /q
rmdir clinical-impression-status /s /q
rmdir code /s /q
rmdir CodeableConcept /s /q
rmdir Coding /s /q
rmdir Communication /s /q
rmdir CommunicationRequest /s /q
rmdir communication-request-status /s /q
rmdir communication-status /s /q
rmdir compartment /s /q
rmdir Composition /s /q
rmdir composition-attestation-mode /s /q
rmdir composition-status /s /q
rmdir ConceptMap /s /q
rmdir concept-map-equivalence /s /q
rmdir Condition /s /q
rmdir conditional-delete-status /s /q
rmdir condition-category /s /q
rmdir condition-clinical /s /q
rmdir condition-state /s /q
rmdir condition-ver-status /s /q
rmdir Conformance /s /q
rmdir conformance-expectation /s /q
rmdir conformance-resource-status /s /q
rmdir conformance-statement-kind /s /q
rmdir constraint-severity /s /q
rmdir contactentity-type /s /q
rmdir ContactPoint /s /q
rmdir contact-point-system /s /q
rmdir contact-point-use /s /q
rmdir content-type /s /q
rmdir Contract /s /q
rmdir contractsignertypecodes /s /q
rmdir contractsubtypecodes /s /q
rmdir contracttermsubtypecodes /s /q
rmdir contracttermtypecodes /s /q
rmdir contracttypecodes /s /q
rmdir Count /s /q
rmdir Coverage /s /q
rmdir daf /s /q
rmdir data-absent-reason /s /q
rmdir DataElement /s /q
rmdir dataelement-stringency /s /q
rmdir data-types /s /q
rmdir date /s /q
rmdir dateTime /s /q
rmdir days-of-week /s /q
rmdir decimal /s /q
rmdir DetectedIssue /s /q
rmdir detectedissue-severity /s /q
rmdir Device /s /q
rmdir device-action /s /q
rmdir DeviceComponent /s /q
rmdir DeviceMetric /s /q
rmdir devicestatus /s /q
rmdir DeviceUseRequest /s /q
rmdir device-use-request-priority /s /q
rmdir device-use-request-status /s /q
rmdir DeviceUsage /s /q
rmdir DiagnosticOrder /s /q
rmdir diagnostic-order-priority /s /q
rmdir diagnostic-order-status /s /q
rmdir DiagnosticReport /s /q
rmdir diagnostic-report-status /s /q
rmdir diet /s /q
rmdir digital-media-type /s /q
rmdir discharge-disposition /s /q
rmdir dist /s /q
rmdir Distance /s /q
rmdir DocumentManifest /s /q
rmdir document-mode /s /q
rmdir DocumentReference /s /q
rmdir document-reference-status /s /q
rmdir document-relationship-type /s /q
rmdir Duration /s /q
rmdir ehrsrle /s /q
rmdir Element /s /q
rmdir ElementDefinition /s /q
rmdir EligibilityRequest /s /q
rmdir EligibilityResponse /s /q
rmdir Encounter /s /q
rmdir encounter-class /s /q
rmdir encounter-location-status /s /q
rmdir encounter-priority /s /q
rmdir encounter-special-arrangements /s /q
rmdir encounter-state /s /q
rmdir encounter-type /s /q
rmdir EnrollmentRequest /s /q
rmdir EnrollmentResponse /s /q
rmdir entformula-additive /s /q
rmdir EpisodeOfCare /s /q
rmdir episode-of-care-status /s /q
rmdir examples /s /q
rmdir exception /s /q
rmdir ex-fdi /s /q
rmdir ex-oralprostho /s /q
rmdir ex-pharmaservice /s /q
rmdir ExplanationOfBenefit /s /q
rmdir ex-serviceproduct /s /q
rmdir ex-surface /s /q
rmdir Extension /s /q
rmdir extension-context /s /q
rmdir external /s /q
rmdir ex-udi /s /q
rmdir ex-USCLS /s /q
rmdir ex-visionprescriptionproduct /s /q
rmdir FamilyMemberHistory /s /q
rmdir FDI-surface /s /q
rmdir filter-operator /s /q
rmdir Flag /s /q
rmdir flag-category /s /q
rmdir flag-priority-code /s /q
rmdir flag-status /s /q
rmdir fm-conditions /s /q
rmdir forms-codes /s /q
rmdir fundsreserve /s /q
rmdir Goal /s /q
rmdir goal-acceptance-status /s /q
rmdir goal-category /s /q
rmdir goal-priority /s /q
rmdir goal-relationship-type /s /q
rmdir goal-status /s /q
rmdir goal-status-reason /s /q
rmdir Group /s /q
rmdir group-type /s /q
rmdir guide-dependency-type /s /q
rmdir guide-page-kind /s /q
rmdir guide-resource-purpose /s /q
rmdir HealthcareService /s /q
rmdir history-status /s /q
rmdir html /s /q
rmdir http-verb /s /q
rmdir HumanName /s /q
rmdir id /s /q
rmdir Identifier /s /q
rmdir identifier-type /s /q
rmdir identifier-use /s /q
rmdir identity-assuranceLevel /s /q
rmdir images /s /q
rmdir ImagingObjectSelection /s /q
rmdir ImagingStudy /s /q
rmdir Immunization /s /q
rmdir ImmunizationRecommendation /s /q
rmdir immunization-recommendation-date-criterion /s /q
rmdir immunization-recommendation-status /s /q
rmdir ImplementationGuide /s /q
rmdir instant /s /q
rmdir integer /s /q
rmdir intervention /s /q
rmdir issue-severity /s /q
rmdir issue-type /s /q
rmdir less /s /q
rmdir less-glyphicons /s /q
rmdir less-joyo /s /q
rmdir link-type /s /q
rmdir List /s /q
rmdir list-empty-reason /s /q
rmdir list-example-use-codes /s /q
rmdir list-mode /s /q
rmdir list-order /s /q
rmdir list-status /s /q
rmdir Location /s /q
rmdir location-mode /s /q
rmdir location-physical-type /s /q
rmdir location-status /s /q
rmdir marital-status /s /q
rmdir markdown /s /q
rmdir measurement-principle /s /q
rmdir Media /s /q
rmdir media-subtype /s /q
rmdir Medication /s /q
rmdir MedicationAdministration /s /q
rmdir medication-admin-status /s /q
rmdir MedicationDispense /s /q
rmdir medication-dispense-status /s /q
rmdir MedicationOrder /s /q
rmdir medication-order-status /s /q
rmdir MedicationStatement /s /q
rmdir medication-statement-status /s /q
rmdir message-conformance-event-mode /s /q
rmdir message-events /s /q
rmdir MessageHeader /s /q
rmdir message-reasons-encounter /s /q
rmdir message-significance-category /s /q
rmdir message-transport /s /q
rmdir Meta /s /q
rmdir metric-calibration-state /s /q
rmdir metric-calibration-type /s /q
rmdir metric-category /s /q
rmdir metric-color /s /q
rmdir metric-operational-status /s /q
rmdir missingtoothreason /s /q
rmdir modifiers /s /q
rmdir Money /s /q
rmdir name-use /s /q
rmdir NamingSystem /s /q
rmdir namingsystem-identifier-type /s /q
rmdir namingsystem-type /s /q
rmdir Narrative /s /q
rmdir narrative-status /s /q
rmdir ndfrt /s /q
rmdir network-type /s /q
rmdir nil /s /q
rmdir note-type /s /q
rmdir NutritionOrder /s /q
rmdir nutrition-order-status /s /q
rmdir object-lifecycle /s /q
rmdir object-role /s /q
rmdir object-type /s /q
rmdir Observation /s /q
rmdir observation-category /s /q
rmdir observation-relationshiptypes /s /q
rmdir observation-status /s /q
rmdir oid /s /q
rmdir OperationDefinition /s /q
rmdir operation-kind /s /q
rmdir OperationOutcome /s /q
rmdir operation-outcome /s /q
rmdir operation-parameter-use /s /q
rmdir Order /s /q
rmdir OrderResponse /s /q
rmdir order-status /s /q
rmdir Organization /s /q
rmdir organization-type /s /q
rmdir Parameters /s /q
rmdir participantrequired /s /q
rmdir participantstatus /s /q
rmdir participant-type /s /q
rmdir participationstatus /s /q
rmdir Patient /s /q
rmdir patient-contact-relationship /s /q
rmdir patient-mpi-match /s /q
rmdir payeetype /s /q
rmdir PaymentNotice /s /q
rmdir PaymentReconciliation /s /q
rmdir paymentstatus /s /q
rmdir payment-type /s /q
rmdir Period /s /q
rmdir Person /s /q
rmdir positiveInt /s /q
rmdir Practitioner /s /q
rmdir practitioner-role /s /q
rmdir practitioner-specialty /s /q
rmdir Procedure /s /q
rmdir procedure-progress-status-code /s /q
rmdir procedure-relationship-type /s /q
rmdir ProcedureRequest /s /q
rmdir procedure-request-priority /s /q
rmdir procedure-request-status /s /q
rmdir procedure-status /s /q
rmdir processoutcomecodes /s /q
rmdir processpriority /s /q
rmdir ProcessRequest /s /q
rmdir ProcessResponse /s /q
rmdir property-representation /s /q
rmdir Provenance /s /q
rmdir provenance-entity-role /s /q
rmdir provenance-participant-role /s /q
rmdir provenance-participant-type /s /q
rmdir qicore /s /q
rmdir Quantity /s /q
rmdir quantity-comparator /s /q
rmdir question-max-occurs /s /q
rmdir Questionnaire /s /q
rmdir questionnaire-answers-status /s /q
rmdir questionnaire-question-control /s /q
rmdir QuestionnaireResponse /s /q
rmdir questionnaire-status /s /q
rmdir Range /s /q
rmdir Ratio /s /q
rmdir reaction-event-certainty /s /q
rmdir reaction-event-severity /s /q
rmdir reason-medication-given /s /q
rmdir reason-medication-not-given /s /q
rmdir Redirect /s /q
rmdir Reference /s /q
rmdir referencerange-meaning /s /q
rmdir ReferralRequest /s /q
rmdir referralstatus /s /q
rmdir registry /s /q
rmdir RelatedPerson /s /q
rmdir relationship /s /q
rmdir remittance-outcome /s /q
rmdir resource-aggregation-mode /s /q
rmdir resource-slicing-rules /s /q
rmdir resource-types /s /q
rmdir resource-validation-mode /s /q
rmdir response-code /s /q
rmdir restful-conformance-mode /s /q
rmdir restful-interaction /s /q
rmdir restful-security-service /s /q
rmdir RiskAssessment /s /q
rmdir risk-probability /s /q
rmdir ruleset /s /q
rmdir SampledData /s /q
rmdir Schedule /s /q
rmdir sdc /s /q
rmdir sdcde /s /q
rmdir search /s /q
rmdir search-entry-mode /s /q
rmdir search-modifier-code /s /q
rmdir SearchParameter /s /q
rmdir search-param-type /s /q
rmdir search-xpath-usage /s /q
rmdir security-source-type /s /q
rmdir service-provision-conditions /s /q
rmdir service-referral-method /s /q
rmdir sid /s /q
rmdir Signature /s /q
rmdir SimpleQuantity /s /q
rmdir Slot /s /q
rmdir slotstatus /s /q
rmdir special-values /s /q
rmdir Specimen /s /q
rmdir specimen-status /s /q
rmdir string /s /q
rmdir StructureDefinition /s /q
rmdir structure-definition-kind /s /q
rmdir Subscription /s /q
rmdir subscription-channel-type /s /q
rmdir subscription-status /s /q
rmdir subscription-tag /s /q
rmdir Substance /s /q
rmdir substance-category /s /q
rmdir SupplyDelivery /s /q
rmdir supplydelivery-status /s /q
rmdir supply-item-type /s /q
rmdir supply-kind /s /q
rmdir SupplyRequest /s /q
rmdir supplyrequest-reason /s /q
rmdir supplyrequest-status /s /q
rmdir TestScript /s /q
rmdir testscript-operation-codes /s /q
rmdir time /s /q
rmdir Timing /s /q
rmdir timing-abbreviation /s /q
rmdir transaction-mode /s /q
rmdir unknown-content-code /s /q
rmdir unsignedInt /s /q
rmdir uri /s /q
rmdir uslab /s /q
rmdir uuid /s /q
rmdir v2 /s /q
rmdir v3 /s /q
rmdir vaccination-protocol-dose-status /s /q
rmdir vaccination-protocol-dose-status-reason /s /q
rmdir ValueSet /s /q
rmdir valueset-signature-type /s /q
rmdir versioning-policy /s /q
rmdir vision-base-codes /s /q
rmdir vision-eye-codes /s /q
rmdir VisionPrescription /s /q
rmdir xds-relationship-type /s /q

REM copy the new FHIR spec
xcopy fhir3 /s /e /v /y 

REM delete the temp FHIR spec
rmdir fhir3 /s /q