@startuml DiagnosticModuleAbstracted
!pragma layout smetana
hide empty fields
hide empty methods
top to bottom direction

protocol DerivedImagingMeasurement ##Green {}
protocol ImagingMeasurementGroup ##Green {}
protocol ImagingQualitativeEvaluation ##Green {}
protocol ImagingMeasurement ##Green{}
abstract class ImagingObservation ##Green {}
record Observation ##Green{}

DerivedImagingMeasurement --> ImagingMeasurementGroup : derivedFrom
ImagingMeasurementGroup --> ImagingQualitativeEvaluation : hasMember
ImagingMeasurementGroup --> ImagingMeasurement : hasMember


ImagingObservation --> ObservationImagingSelection : derivedFrom

ImagingObservation --|> ImagingQualitativeEvaluation
ImagingObservation --|> ImagingMeasurement
ImagingObservation --|> ImagingMeasurementGroup

Observation --|> ImagingObservation
Observation --|> DerivedImagingMeasurement

abstract class ObservationImagingSelection ##BlueViolet {}
record ImagingSelection ##BlueViolet{}

ImagingSelection --|> ObservationImagingSelection


protocol FindingSite ##Orange{}
record BodyStructure ##Orange{}
ObservationImagingSelection --> FindingSite
BodyStructure --|> FindingSite

legend right
R = FHIR Resource
P = Resource Profile
A = Abstract Profile
endlegend

@enduml
