@startuml dicom_information_entity_to_fhir_resource_mapping
left to right direction
package "DICOM Information Entity (IE) List<sup>1</sup>" {
    object "Patient" as patientIE
    object "Visit" as visitIE
    object "Study" as studyIE
    object "Series" as seriesIE
    object "Equipment" as equipmentIE
    object "Instance<sup>2</sup>" as instanceIE
}
object Patient {
    identifier = Patient ID
}

object Encounter {
    identifier = Visit ID
}

object ImagingStudy {
    identifier = Study Instance UID
    series[*].uid = Series Instance UID
    series[*].instance[*].uid = SOP Instance UID
}
object ServiceRequest {
    identifier = Accession Number
}

object Procedure {
    code = Performed Procedure Sequence
}

object Device {
    identifier = Device UID
}

patientIE -r[hidden]-> visitIE
visitIE -r[hidden]-> studyIE
studyIE -r[hidden]-> seriesIE
seriesIE -r[hidden]-> equipmentIE
equipmentIE -r[hidden]-> instanceIE

patientIE --> Patient
visitIE --> Encounter
studyIE --> ImagingStudy
studyIE --> ServiceRequest
studyIE --> Procedure
seriesIE --> ImagingStudy
equipmentIE --> Device
instanceIE --> ImagingStudy

Patient -r[hidden]-> Encounter
Encounter -r[hidden]-> ServiceRequest
ServiceRequest -r[hidden]-> ImagingStudy
ImagingStudy -r[hidden]-> Device

footer
# DICOM Information entities without a corresponding FHIR resource are not shown in this diagram. e.g. Frame of Reference.
# The DICOM information model includes a separate IE for all instance types. e.g. image, presentation state, radiotherapy object, etc. For simplicity, these are represented as a single "Instance" IE in this diagram.
endfooter
@enduml