@startuml
hide footbox
participant "Data Consumer" as Consumer
participant "Data Source" as Source
loop
  Consumer -> Source: 1a. GET base/SomeResource?[some set of filters]&_lastUpdated=gt[most recent update timestamp]
  alt No updates
    Consumer <-- Source: 1b. Empty search-response bundle
  else 
    Consumer <-- Source: 1c. search-response Bundle with new records\n(use most recent meta.lastUpdated in filter for subsequent polls)
  end
end
@enduml