@startuml
hide footbox
participant "Data Consumer" as Consumer
participant "Data Source" as Source
Source -> Consumer: 1a. POST/PUT/PATCH resource/Bundle
Source <-- Consumer: 1b. HTTP 200/201 (possibly with result resource/Bundle)
@enduml