@startuml
hide footbox
participant "Data Consumer" as Consumer
participant "Data Source" as Source
Consumer -> Source: 1a. POST Subscription
Consumer <-- Source: 1b. HTTP 201 Created
loop
  ...
  Source --> Source: 2. Relevant event occurs
  Consumer <- Source: 3. Notification of relevant event (no PHI)
  ...
  Consumer -> Source: 4a. Query for recent event data
  Consumer <-- Source: 4b search-set Bundle containing relevant data
end
@enduml